### ISSUE TITLE
MAX_CONNS not working

### ISSUE THREAD

**Issue by hingston** [jneight/django-db-geventpool#26]
I have MAX_CONNS set to 15 but for some reason it is reaching 20+ on my Google Cloud App Engine instance. https://imgur.com/a/wKcPC

OperationalError: FATAL: remaining connection slots are reserved for non-replication superuser connections

```
Traceback (most recent call last):
  File "/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/env/lib/python3.6/site-packages/django/views/decorators/cache.py", line 31, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/home/vmagent/app/checker/views.py", line 34, in search
    context = process_summoner(lookup_summoner(parsed_name_result, region), name)
  File "/home/vmagent/app/checker/views.py", line 193, in lookup_summoner
    if summoner_set.count() == 1:
  File "/env/lib/python3.6/site-packages/django/db/models/query.py", line 387, in count
    return self.query.get_count(using=self.db)
  File "/env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 491, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 476, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/env/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1061, in execute_sql
    cursor = self.connection.cursor()
  File "/env/lib/python3.6/site-packages/django/db/backends/base/base.py", line 255, in cursor
    return self._cursor()
  File "/env/lib/python3.6/site-packages/django/db/backends/base/base.py", line 232, in _cursor
    self.ensure_connection()
  File "/env/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/env/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/env/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/env/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/env/lib/python3.6/site-packages/django_db_geventpool/backends/postgresql_psycopg2/base.py", line 159, in get_new_connection
    self.connection = self.pool.get()
  File "/env/lib/python3.6/site-packages/django_db_geventpool/backends/postgresql_psycopg2/psycopg2_pool.py", line 50, in get
    new_item = self.create_connection()
  File "/env/lib/python3.6/site-packages/django_db_geventpool/backends/postgresql_psycopg2/psycopg2_pool.py", line 84, in create_connection
    conn = self.connect(*self.args, **self.kwargs)
  File "/env/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
  File "/env/lib/python3.6/site-packages/psycogreen/gevent.py", line 29, in gevent_wait_callback
    state = conn.poll()
django.db.utils.OperationalError: FATAL:  remaining connection slots are reserved for non-replication superuser connections
```

```
Traceback (most recent call last):
  File "/env/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/env/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/env/lib/python3.6/site-packages/django_db_geventpool/backends/postgresql_psycopg2/base.py", line 159, in get_new_connection
    self.connection = self.pool.get()
  File "/env/lib/python3.6/site-packages/django_db_geventpool/backends/postgresql_psycopg2/psycopg2_pool.py", line 50, in get
    new_item = self.create_connection()
  File "/env/lib/python3.6/site-packages/django_db_geventpool/backends/postgresql_psycopg2/psycopg2_pool.py", line 84, in create_connection
    conn = self.connect(*self.args, **self.kwargs)
  File "/env/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
  File "/env/lib/python3.6/site-packages/psycogreen/gevent.py", line 29, in gevent_wait_callback
    state = conn.poll()
psycopg2.OperationalError: FATAL:  remaining connection slots are reserved for non-replication superuser connections
```

Django settings.py:
```
    DATABASES = {
        'default': {
            'ENGINE': 'django_db_geventpool.backends.postgresql_psycopg2',
            'NAME': 'db1',
            'USER': 'lolnames',
            'PASSWORD': 'XXXXXXXXXXXXXXXXXX',
            'HOST': '/cloudsql/lolnames:us-central1:loldb',
            'PORT': '5432',
            'ATOMIC_REQUESTS': False,
            'CONN_MAX_AGE': 0,
            'OPTIONS': {
                'MAX_CONNS': 15,
                'connect_timeout': 5,
            }
        }
    }
```

requirements.txt:

```
pip==9.0.1
mysqlclient==1.3.12
Django==2.0.1
django-db-geventpool==2
django-removewww==0.1.2
gevent==1.2.2
gunicorn==19.7.1
psycopg2==2.7.3.2
python-dateutil==2.6.1
pytz==2017.3
regex==2017.12.12
requests-toolbelt==0.8.0
requests[security]
six==1.11.0
wheel==0.30.0
```

**Comment by jneight** [comment]
Is your webserver using more than one process?, in that case, each process is independent and the DB connections cannot be shared, so, 2 processes with 15 connections each one, can open 30 connections

**Comment by ConfidenceYobo** [comment]
Does this affect if one is running multiple gunicorn workers?
